<a href="https://colab.research.google.com/github/Divyanshpanchal960/python/blob/main/DUMMIES%20.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd


In [ ]:
df=np.array([1,2,3,4,5,6,7,8,9])
type(df)
df.ndim
df.size
df.shape
df*5
df+5
df-5
df/5
df//5
df**2
df**3
df**4
df<=8
df>=8
df<6
df>5
df!=5

array([ True,  True,  True,  True, False,  True,  True,  True,  True])

In [ ]:
df
df=np.eye(10)
df

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [ ]:
df=np.zeros((3,3))
df
df=np.ones((3,3))
df

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
df=np.random.randint(1,10,9)
df

array([4, 3, 3, 6, 6, 2, 5, 5, 7])

In [ ]:
df=np.random.rand(9).reshape(3,3)
df

array([[0.47626689, 0.01175291, 0.03086006],
       [0.43170506, 0.14419055, 0.75860715],
       [0.74533726, 0.34612793, 0.20414772]])

In [ ]:
df=np.arange(2,20,2)
df
df.reshape(3,3)

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [ ]:
df1=([1,2,3,4,5,6,7,8,9])
df2=df.dot(df1)
df2

np.int64(570)

In [ ]:
df1=np.array([10,20,30,40,50,60,70,10,10,20,20,30,40,5,0,0,0,70,49])
df1
df1=np.unique(df1,return_index=True,return_counts=True)
df1

(array([ 0,  5, 10, 20, 30, 40, 49, 50, 60, 70]),
 array([14, 13,  0,  1,  2,  3, 18,  4,  5,  6]),
 array([3, 1, 3, 3, 2, 2, 1, 1, 1, 2]))

In [ ]:
import pandas as pd
df=pd.read_csv("/content/credit_scoring - credit_scoring.csv")
df.head(4)

Age  Gender Marital Status Education Level Employment Status  \
0   60    Male        Married          Master          Employed   
1   25    Male        Married     High School        Unemployed   
2   30  Female         Single          Master          Employed   
3   58  Female        Married             PhD        Unemployed   

   Credit Utilization Ratio  Payment History  Number of Credit Accounts  \
0                      0.22             2685                          2   
1                      0.20             2371                          9   
2                      0.22             2771                          6   
3                      0.12             1371                          2   

   Loan Amount  Interest Rate  Loan Term   Type of Loan  
0      4675000           2.65         48  Personal Loan  
1      3619000           5.19         60      Auto Loan  
2       957000           2.76         12      Auto Loan  
3      4731000           6.57         60      Auto Loan

In [ ]:
df.isnull().sum()

Age                          0
Gender                       0
Marital Status               0
Education Level              0
Employment Status            0
Credit Utilization Ratio     0
Payment History              0
Number of Credit Accounts    0
Loan Amount                  0
Interest Rate                0
Loan Term                    0
Type of Loan                 0
dtype: int64

In [ ]:
df.head(4)

Gender Marital Status Education Level Employment Status   Type of Loan
0    Male        Married          Master          Employed  Personal Loan
1    Male        Married     High School        Unemployed      Auto Loan
2  Female         Single          Master          Employed      Auto Loan
3  Female        Married             PhD        Unemployed      Auto Loan

In [ ]:
df=df.drop(columns=['Age','Credit Utilization Ratio','Payment History','Number of Credit Accounts','Loan Amount','Interest Rate','Loan Term'])

In [ ]:
df.head(3)

Gender Marital Status Education Level Employment Status   Type of Loan
0    Male        Married          Master          Employed  Personal Loan
1    Male        Married     High School        Unemployed      Auto Loan
2  Female         Single          Master          Employed      Auto Loan

In [ ]:
x=df.drop(columns=['Type of Loan'])
x.head(4)
y=df['Type of Loan']
y.head(4)

0    Personal Loan
1        Auto Loan
2        Auto Loan
3        Auto Loan
Name: Type of Loan, dtype: object

In [ ]:
x.head(3)

Gender Marital Status Education Level Employment Status
0    Male        Married          Master          Employed
1    Male        Married     High School        Unemployed
2  Female         Single          Master          Employed

In [ ]:
df['Gender'].value_counts()

Gender
Male      501
Female    499
Name: count, dtype: int64

In [ ]:
df['Employment Status'].value_counts()

Employment Status
Self-Employed    347
Employed         328
Unemployed       325
Name: count, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=23)

In [ ]:
from sklearn.preprocessing  import OrdinalEncoder
ol=OrdinalEncoder(categories=[['Male','Female'],
                  ['Married','Divorced','Single'],
                  ['Master','High School','PhD','Bachelor'],
                   ['Self-Employed','Employed','Unemployed']])

In [ ]:
x_train=ol.fit_transform(x_train)

In [ ]:
x_train.shape

(800, 4)

In [ ]:
# from sklearn.model_selection import train_test_split
# x_train, x_test, y_train, y_test=train_test_split(x,y,test_size=0.2,random_state=23)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()

x_train_sc=sc.fit_transform(x_train_encoded)
x_train_new=pd.DataFrame(x_train_sc,columns=x_train_encoded.columns)

ValueError: could not convert string to float: 'Male'

In [ ]:
x_train_new
np.round(x_train_new.describe(),2)

Gender  Marital Status  Education Level  Employment Status
count  800.00          800.00           800.00             800.00
mean     0.00           -0.00            -0.00              -0.00
std      1.00            1.00             1.00               1.00
min     -0.99           -1.20            -1.27              -1.19
25%     -0.99           -1.20            -1.27              -1.19
50%     -0.99            0.03            -0.38               0.04
75%      1.02            1.26             0.51               1.27
max      1.02            1.26             1.41               1.27

In [ ]:
from sklearn.preprocessing import MinMaxScaler
ms=MinMaxScaler()
x_train_ms=ms.fit_transform(x_train)
x_train_new=pd.DataFrame(x_train_ms,columns=x.columns)
np.round(x_train_new.describe(),2)

Gender  Marital Status  Education Level  Employment Status
count  800.00          800.00           800.00             800.00
mean     0.49            0.49             0.47               0.48
std      0.50            0.41             0.37               0.41
min      0.00            0.00             0.00               0.00
25%      0.00            0.00             0.00               0.00
50%      0.00            0.50             0.33               0.50
75%      1.00            1.00             0.67               1.00
max      1.00            1.00             1.00               1.00

In [ ]:
x_train_new=pd.get_dummies(x_train_new,columns=['Gender','Marital Status','Education Level','Employment Status'])

In [ ]:
x_train_new

Gender_0.0  Gender_1.0  Marital Status_0.0  Marital Status_0.5  \
0          True       False               False                True   
1          True       False               False               False   
2          True       False               False                True   
3          True       False               False                True   
4         False        True               False               False   
..          ...         ...                 ...                 ...   
795        True       False                True               False   
796        True       False                True               False   
797        True       False                True               False   
798        True       False               False                True   
799        True       False                True               False   

     Marital Status_1.0  Education Level_0.0  \
0                 False                False   
1                  True                False   
2                 False                False   
3                 False                False   
4                  True                False   
..                  ...                  ...   
795               False                 True   
796               False                False   
797               False                False   
798               False                 True   
799               False                False   

     Education Level_0.3333333333333333  Education Level_0.6666666666666666  \
0                                 False                               False   
1                                 False                               False   
2                                 False                                True   
3                                 False                                True   
4                                 False                                True   
..                                  ...                                 ...   
795                               False                               False   
796                               False                               False   
797                                True                               False   
798                               False                               False   
799                               False                                True   

     Education Level_1.0  Employment Status_0.0  Employment Status_0.5  \
0                   True                   True                  False   
1                   True                  False                  False   
2                  False                   True                  False   
3                  False                  False                   True   
4                  False                  False                   True   
..                   ...                    ...                    ...   
795                False                   True                  False   
796                 True                  False                   True   
797                False                  False                   True   
798                False                   True                  False   
799                False                  False                  False   

     Employment Status_1.0  
0                    False  
1                     True  
2                    False  
3                    False  
4                    False  
..                     ...  
795                  False  
796                  False  
797                  False  
798                  False  
799                   True  

[800 rows x 12 columns]

In [ ]:
x_train_valid=pd.get_dummies(x_train_new,columns=['Gender','Marital Status','Education Level','Employment Status'],drop_first=True)

KeyError: "None of [Index(['Gender', 'Marital Status', 'Education Level', 'Employment Status'], dtype='object')] are in the [columns]"

In [ ]:
# Apply one-hot encoding to the training and testing data
x_train_encoded = pd.get_dummies(x_train, columns=['Gender', 'Marital Status', 'Education Level', 'Employment Status'], drop_first=True)
x_test_encoded = pd.get_dummies(x_test, columns=['Gender', 'Marital Status', 'Education Level', 'Employment Status'], drop_first=True)

In [ ]:
x_train_encoded
x_train_encode.astype(int)

NameError: name 'x_train_encode' is not defined

In [ ]:
x_train_encoded.astype(int)

Gender_Male  Marital Status_Married  Marital Status_Single  \
228            1                       0                      0   
45             1                       0                      1   
373            1                       0                      0   
813            1                       0                      0   
448            0                       0                      1   
..           ...                     ...                    ...   
950            1                       1                      0   
969            1                       1                      0   
40             1                       1                      0   
742            1                       0                      0   
595            1                       1                      0   

     Education Level_High School  Education Level_Master  Education Level_PhD  \
228                            0                       0                    0   
45                             0                       0                    0   
373                            0                       0                    1   
813                            0                       0                    1   
448                            0                       0                    1   
..                           ...                     ...                  ...   
950                            0                       1                    0   
969                            0                       0                    0   
40                             1                       0                    0   
742                            0                       1                    0   
595                            0                       0                    1   

     Employment Status_Self-Employed  Employment Status_Unemployed  
228                                1                             0  
45                                 0                             1  
373                                1                             0  
813                                0                             0  
448                                0                             0  
..                               ...                           ...  
950                                1                             0  
969                                0                             0  
40                                 0                             0  
742                                1                             0  
595                                0                             1  

[800 rows x 8 columns]

In [2]:
import pandas as pd
import numpy as np


In [3]:
df=pd.read_csv("/content/credit_scoring - credit_scoring.csv")

In [4]:
df.head(3)

Age  Gender Marital Status Education Level Employment Status  \
0   60    Male        Married          Master          Employed   
1   25    Male        Married     High School        Unemployed   
2   30  Female         Single          Master          Employed   

   Credit Utilization Ratio  Payment History  Number of Credit Accounts  \
0                      0.22             2685                          2   
1                      0.20             2371                          9   
2                      0.22             2771                          6   

   Loan Amount  Interest Rate  Loan Term   Type of Loan  
0      4675000           2.65         48  Personal Loan  
1      3619000           5.19         60      Auto Loan  
2       957000           2.76         12      Auto Loan

In [5]:
df.isnull().sum()

Age                          0
Gender                       0
Marital Status               0
Education Level              0
Employment Status            0
Credit Utilization Ratio     0
Payment History              0
Number of Credit Accounts    0
Loan Amount                  0
Interest Rate                0
Loan Term                    0
Type of Loan                 0
dtype: int64

In [9]:
x=df.drop(columns=["Type of Loan"])
x.head(3)
y=df['Type of Loan']
y.head(3)

0    Personal Loan
1        Auto Loan
2        Auto Loan
Name: Type of Loan, dtype: object

In [10]:
x.head(3)

Age  Gender Marital Status Education Level Employment Status  \
0   60    Male        Married          Master          Employed   
1   25    Male        Married     High School        Unemployed   
2   30  Female         Single          Master          Employed   

   Credit Utilization Ratio  Payment History  Number of Credit Accounts  \
0                      0.22             2685                          2   
1                      0.20             2371                          9   
2                      0.22             2771                          6   

   Loan Amount  Interest Rate  Loan Term  
0      4675000           2.65         48  
1      3619000           5.19         60  
2       957000           2.76         12

In [12]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=43)

In [18]:
a=pd.get_dummies(x_train,columns=['Age','Gender','Marital Status','Education Level','Employment Status','Credit Utilization Ratio','Payment History','Number of Credit Accounts','Loan Amount','Interest Rate','Loan Term'])

In [19]:
a.head(3)

Age_20  Age_21  Age_22  Age_23  Age_24  Age_25  Age_26  Age_27  Age_28  \
147   False   False   False   False   False   False   False   False   False   
88    False   False   False   False   False   False   False   False   False   
731   False   False   False   False   False   False   False   False    True   

     Age_29  ...  Interest Rate_19.88  Interest Rate_19.92  \
147   False  ...                False                False   
88    False  ...                False                False   
731   False  ...                False                False   

     Interest Rate_19.93  Interest Rate_19.98  Interest Rate_19.99  \
147                 True                False                False   
88                 False                False                False   
731                False                False                False   

     Loan Term_12  Loan Term_24  Loan Term_36  Loan Term_48  Loan Term_60  
147         False         False          True         False         False  
88          False          True         False         False         False  
731         False         False         False          True         False  

[3 rows x 1652 columns]

In [20]:
b=pd.get_dummies(x_train,columns=['Age','Gender','Marital Status','Education Level','Employment Status','Credit Utilization Ratio','Payment History','Number of Credit Accounts','Loan Amount','Interest Rate','Loan Term'])

In [21]:
b.head(3)

Age_20  Age_21  Age_22  Age_23  Age_24  Age_25  Age_26  Age_27  Age_28  \
147   False   False   False   False   False   False   False   False   False   
88    False   False   False   False   False   False   False   False   False   
731   False   False   False   False   False   False   False   False    True   

     Age_29  ...  Interest Rate_19.88  Interest Rate_19.92  \
147   False  ...                False                False   
88    False  ...                False                False   
731   False  ...                False                False   

     Interest Rate_19.93  Interest Rate_19.98  Interest Rate_19.99  \
147                 True                False                False   
88                 False                False                False   
731                False                False                False   

     Loan Term_12  Loan Term_24  Loan Term_36  Loan Term_48  Loan Term_60  
147         False         False          True         False         False  
88          False          True         False         False         False  
731         False         False         False          True         False  

[3 rows x 1652 columns]

In [24]:
b.astype(int)


Age_20  Age_21  Age_22  Age_23  Age_24  Age_25  Age_26  Age_27  Age_28  \
147       0       0       0       0       0       0       0       0       0   
88        0       0       0       0       0       0       0       0       0   
731       0       0       0       0       0       0       0       0       1   
741       0       0       0       0       0       0       0       0       0   
36        0       0       0       0       0       0       0       0       0   
..      ...     ...     ...     ...     ...     ...     ...     ...     ...   
277       0       0       0       0       0       0       0       0       0   
817       0       0       0       0       0       0       0       0       0   
255       0       0       0       0       0       0       0       0       0   
320       0       0       0       0       0       0       0       0       0   
836       0       0       0       0       0       0       0       0       0   

     Age_29  ...  Interest Rate_19.88  Interest Rate_19.92  \
147       0  ...                    0                    0   
88        0  ...                    0                    0   
731       0  ...                    0                    0   
741       0  ...                    0                    0   
36        0  ...                    0                    0   
..      ...  ...                  ...                  ...   
277       0  ...                    0                    0   
817       0  ...                    0                    0   
255       0  ...                    0                    0   
320       0  ...                    0                    0   
836       0  ...                    0                    0   

     Interest Rate_19.93  Interest Rate_19.98  Interest Rate_19.99  \
147                    1                    0                    0   
88                     0                    0                    0   
731                    0                    0                    0   
741                    0                    0                    0   
36                     0                    0                    0   
..                   ...                  ...                  ...   
277                    0                    0                    0   
817                    0                    0                    0   
255                    0                    0                    0   
320                    0                    0                    0   
836                    0                    0                    0   

     Loan Term_12  Loan Term_24  Loan Term_36  Loan Term_48  Loan Term_60  
147             0             0             1             0             0  
88              0             1             0             0             0  
731             0             0             0             1             0  
741             0             0             0             0             1  
36              1             0             0             0             0  
..            ...           ...           ...           ...           ...  
277             1             0             0             0             0  
817             0             0             0             1             0  
255             0             0             0             1             0  
320             0             0             0             1             0  
836             0             0             0             0             1  

[800 rows x 1652 columns]

In [26]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
b_train_sc=sc.fit_transform(b)
b_train_new=pd.DataFrame(b_train_sc,columns=b.columns)

In [27]:
np.round(b_train_new.describe(),2)

Age_20  Age_21  Age_22  Age_23  Age_24  Age_25  Age_26  Age_27  Age_28  \
count  800.00  800.00  800.00  800.00  800.00  800.00  800.00  800.00  800.00   
mean    -0.00   -0.00    0.00    0.00    0.00    0.00   -0.00    0.00    0.00   
std      1.00    1.00    1.00    1.00    1.00    1.00    1.00    1.00    1.00   
min     -0.13   -0.14   -0.12   -0.13   -0.17   -0.15   -0.14   -0.14   -0.18   
25%     -0.13   -0.14   -0.12   -0.13   -0.17   -0.15   -0.14   -0.14   -0.18   
50%     -0.13   -0.14   -0.12   -0.13   -0.17   -0.15   -0.14   -0.14   -0.18   
75%     -0.13   -0.14   -0.12   -0.13   -0.17   -0.15   -0.14   -0.14   -0.18   
max      7.78    7.00    8.10    7.49    5.95    6.59    7.00    7.00    5.57   

       Age_29  ...  Interest Rate_19.88  Interest Rate_19.92  \
count  800.00  ...               800.00               800.00   
mean     0.00  ...                 0.00                 0.00   
std      1.00  ...                 1.00                 1.00   
min     -0.15  ...                -0.04                -0.05   
25%     -0.15  ...                -0.04                -0.05   
50%     -0.15  ...                -0.04                -0.05   
75%     -0.15  ...                -0.04                -0.05   
max      6.79  ...                28.27                19.97   

       Interest Rate_19.93  Interest Rate_19.98  Interest Rate_19.99  \
count               800.00               800.00               800.00   
mean                  0.00                 0.00                 0.00   
std                   1.00                 1.00                 1.00   
min                  -0.04                -0.04                -0.04   
25%                  -0.04                -0.04                -0.04   
50%                  -0.04                -0.04                -0.04   
75%                  -0.04                -0.04                -0.04   
max                  28.27                28.27                28.27   

       Loan Term_12  Loan Term_24  Loan Term_36  Loan Term_48  Loan Term_60  
count         800.0        800.00        800.00        800.00        800.00  
mean            0.0         -0.00          0.00         -0.00          0.00  
std             1.0          1.00          1.00          1.00          1.00  
min            -0.5         -0.48         -0.46         -0.49         -0.56  
25%            -0.5         -0.48         -0.46         -0.49         -0.56  
50%            -0.5         -0.48         -0.46         -0.49         -0.56  
75%            -0.5         -0.48         -0.46         -0.49         -0.56  
max             2.0          2.10          2.15          2.02          1.77  

[8 rows x 1652 columns]

In [28]:
from sklearn.preprocessing import MinMaxScaler
ms=MinMaxScaler()
b_train_ms=ms.fit_transform(b)
b_train_new=pd.DataFrame(b_train_ms,columns=b.columns)

In [29]:
np.round(b_train_new.describe(),2)

Age_20  Age_21  Age_22  Age_23  Age_24  Age_25  Age_26  Age_27  Age_28  \
count  800.00  800.00  800.00  800.00  800.00  800.00  800.00  800.00  800.00   
mean     0.02    0.02    0.02    0.02    0.03    0.02    0.02    0.02    0.03   
std      0.13    0.14    0.12    0.13    0.16    0.15    0.14    0.14    0.17   
min      0.00    0.00    0.00    0.00    0.00    0.00    0.00    0.00    0.00   
25%      0.00    0.00    0.00    0.00    0.00    0.00    0.00    0.00    0.00   
50%      0.00    0.00    0.00    0.00    0.00    0.00    0.00    0.00    0.00   
75%      0.00    0.00    0.00    0.00    0.00    0.00    0.00    0.00    0.00   
max      1.00    1.00    1.00    1.00    1.00    1.00    1.00    1.00    1.00   

       Age_29  ...  Interest Rate_19.88  Interest Rate_19.92  \
count  800.00  ...               800.00               800.00   
mean     0.02  ...                 0.00                 0.00   
std      0.14  ...                 0.04                 0.05   
min      0.00  ...                 0.00                 0.00   
25%      0.00  ...                 0.00                 0.00   
50%      0.00  ...                 0.00                 0.00   
75%      0.00  ...                 0.00                 0.00   
max      1.00  ...                 1.00                 1.00   

       Interest Rate_19.93  Interest Rate_19.98  Interest Rate_19.99  \
count               800.00               800.00               800.00   
mean                  0.00                 0.00                 0.00   
std                   0.04                 0.04                 0.04   
min                   0.00                 0.00                 0.00   
25%                   0.00                 0.00                 0.00   
50%                   0.00                 0.00                 0.00   
75%                   0.00                 0.00                 0.00   
max                   1.00                 1.00                 1.00   

       Loan Term_12  Loan Term_24  Loan Term_36  Loan Term_48  Loan Term_60  
count         800.0        800.00        800.00         800.0        800.00  
mean            0.2          0.18          0.18           0.2          0.24  
std             0.4          0.39          0.38           0.4          0.43  
min             0.0          0.00          0.00           0.0          0.00  
25%             0.0          0.00          0.00           0.0          0.00  
50%             0.0          0.00          0.00           0.0          0.00  
75%             0.0          0.00          0.00           0.0          0.00  
max             1.0          1.00          1.00           1.0          1.00  

[8 rows x 1652 columns]

In [30]:
df.head(2)

Age Gender Marital Status Education Level Employment Status  \
0   60   Male        Married          Master          Employed   
1   25   Male        Married     High School        Unemployed   

   Credit Utilization Ratio  Payment History  Number of Credit Accounts  \
0                      0.22             2685                          2   
1                      0.20             2371                          9   

   Loan Amount  Interest Rate  Loan Term   Type of Loan  
0      4675000           2.65         48  Personal Loan  
1      3619000           5.19         60      Auto Loan