<a href="https://colab.research.google.com/github/Divyanshpanchal960/python/blob/main/numpyqanda.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#array is a Collection of similar datatypes


In [3]:
#Write statement to import numpy?
import numpy as np

In [ ]:
#create an array using numpy?
import numpy as np
array=np.array([1,2,3,4,5,6,7,8,9])
array
type(array)

numpy.ndarray

In [ ]:
#create an array of 10 random integers?
array=np.random.randint(1,20,10)
print(array)
type(array)

[11 13  7  7 19 12 18 18 10  6]


numpy.ndarray

In [ ]:
#create an array of element from 10to20
import numpy as np
array=np.arange(10,20)
print(array)
#b=array.reshape((3,3))
#print(b)

[10 11 12 13 14 15 16 17 18 19]


In [4]:
#create an array which contains value 5,10times
a=np.repeat(5,10)
a




array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [ ]:
#create an one dimenshional array and convert it into 3*3
a=np.arange(1,10).reshape(3,3)
a
# a=np.array([1,2,3,4,5,6,7,8,9])
# type(a)
# a.ndim
print(a.reshape(3,3))


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
#create a 2d array and convert into 3*3 but all the elements should be between 0to1
a=np.random.rand(3,3)
print(a)
print(a.ndim)



[[0.22638685 0.62573212 0.63432303]
 [0.53293968 0.73538555 0.81516559]
 [0.37485618 0.80492251 0.8796494 ]]
2


In [ ]:
#concatenate 2d array horizontally and vertically
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a.ndim)
print(np.hstack(a))
np.vstack(a)

2
[1 2 3 4 5 6 7 8 9]


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
a=np.arange(2,19,2).reshape(3,3)
a

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [ ]:
a=np.arange(1,19,2).reshape(3,3)
a

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

In [ ]:

c=np.array([10,20,30,40,50,50,10,30,20,100])
c
np.unique(c , return_index=True,return_counts=True)

(array([ 10,  20,  30,  40,  50, 100]),
 array([0, 1, 2, 3, 4, 9]),
 array([2, 2, 2, 1, 2, 1]))