<a href="https://colab.research.google.com/github/Divyanshpanchal960/python/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a=np.array([1,2,3,4,5,6,7])
a
type(a)
b=[1,2,3,4]
b
type(b)
type(a)
a
b
a+5
a-5
a*5
a/5
a%5
a//5
a==5
a>5
a<5
a<=5
a>=5
b*5

[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]

In [ ]:
p=[[1,2,3],[3,4,1],[5,6,7]]
q= np.array(p)
q
type(q)
q.ndim  #total dimenshional
q.shape #total rows and columns
#q.size #total elements
#data1.ndim

(3, 3)

In [ ]:
p1=[[1,2,3,4],[2,3,4,5],[1,2,3,4]]
q1=np.array(p1)
q1

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [1, 2, 3, 4]])

In [ ]:
#zeros()--- it will create an array in which all the values will be zero either in one-dimensional or multidimensional



In [ ]:
import numpy as np

In [ ]:
a= np.zeros(4)
a


array([0., 0., 0., 0.])

In [ ]:
a= np.zeros((3,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
a=np.ones((4,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
type(a)

numpy.ndarray

In [ ]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
a=np.array([1,2,3,4,5,6])
a
type(a)
b=np.diag(a)
b

array([[1, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 4, 0, 0],
       [0, 0, 0, 0, 5, 0],
       [0, 0, 0, 0, 0, 6]])

In [ ]:
a=np.random.randint(1,10,4) #generate random numbers given range
a
np.random.seed(23)
a=np.random.randint(1,10,4) #fix or lock random value which we generate in range
a
a=np.random.rand(10) #it generate random value between 0 to 1 of given range
a

array([0.78167951, 0.57390838, 0.44191368, 0.18399514, 0.09982012,
       0.21965262, 0.8333391 , 0.42676537, 0.75457286, 0.99686556])

In [ ]:
#ones()-----it will create an array in which all the values will be one

In [ ]:
#import numpy as np
a=np.ones(2)
a

array([1., 1.])

In [ ]:
a=np.ones((2,3))
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
#eye()----it will create an array in which diagnoal position array will be one and rest all are 0
#import numpy as np
a=np.eye(4)
a


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
#diag()-----using this methond we can set custom elements to diagnoal position
a=np.array([1,23,45,6,1])
b=np.diag(a)
b

array([[ 1,  0,  0,  0,  0],
       [ 0, 23,  0,  0,  0],
       [ 0,  0, 45,  0,  0],
       [ 0,  0,  0,  6,  0],
       [ 0,  0,  0,  0,  1]])

In [ ]:
#random moduals------
#Randint()-------it will generate random numbers in a given range
a=np.random.randint(1,3,4)
a

array([2, 1, 1, 1])

In [ ]:
#Rand----- it wil generate random numbers between 0 to 1
a=np.random.rand(10)
a

array([0.83786398, 0.72682461, 0.12441973, 0.91640842, 0.96824725,
       0.21411034, 0.60544544, 0.88707923, 0.00375732, 0.00852781])

In [ ]:
#seed()---- it will fix or lock your random generate data
np.random.seed(57)
a=np.random.randint(1,10,5)
a

array([7, 6, 7, 9, 3])

In [ ]:
type(a)
a+5
a*5
a//5
a*5
a**2
a**3
a%2
a.ndim
a.shape
a.size
np.random.randint(1,10,9).reshape(3,3)
np.random.seed(32)
s=np.random.randint(1,10,9)
x=s.reshape([3,3])
x
x.ndim






2

In [ ]:
import numpy as np
a=np.array([2,3,4,5,6,7,8,9,10])
a
b=a.reshape(3,3)
b
b.ndim
type(b)
b+5
b*5
b/5
b//5
b%5
b==5
b>=5
b<=5
b>5
b<5
b*5
b.size
b.shape
b.reshape(3,3)
c=np.random.randint(1,10,12)
d=c.reshape([3,4])
d.ndim
d=np.zeros((4,3))
d
d=np.ones((3,3))
d
d=np.eye(4,4)
d
d=np.diag((1,2,3,4,5))
d
d=np.random.rand(3,3)
d
d=np.random.seed(34)
d=np.random.randint(1,30,21)
d
d.ndim
print(d.reshape(7,3))
f=np.array([10,20,20,20,20,20,50,60,70,40,10])
f.ndim
f=np.unique(f,return_index=True,return_counts=True,return_inverse=True)

j=np.linspace(0,1)
j



















[[ 2 27 11]
 [10 23 22]
 [ 5  4  6]
 [12 11 15]
 [19 26 25]
 [ 7 22 23]
 [21  6  1]]


array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])