<a href="https://colab.research.google.com/github/Divyanshpanchal960/python/blob/main/onehotencoder_MLday7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#onehot encoding------> encode our data
#column----> has_covid['yes','no']-----> has_covid_yes,has_covid_no
#get_dummies----> create new column with column name.
#onehot encoding -----> create new column without column name...

In [259]:
import numpy as np
import pandas as pd

In [260]:
df=pd.read_csv("/content/covid_toy - covid_toy.csv")

In [261]:
df=df.drop(columns=['age','fever'])

In [262]:
df.isnull().sum()

gender       0
cough        0
city         0
has_covid    0
dtype: int64

In [263]:
df.head(3)

gender cough     city has_covid
0   Male  Mild  Kolkata        No
1   Male  Mild    Delhi       Yes
2   Male  Mild    Delhi        No

In [264]:
from sklearn.preprocessing import OneHotEncoder

In [265]:
ohe=OneHotEncoder(drop='first', sparse_output=False)

In [266]:
df_new=ohe.fit_transform(df[['gender','cough','city','has_covid']])

In [267]:
df_new

array([[1., 0., 0., 1., 0., 0.],
       [1., 0., 1., 0., 0., 1.],
       [1., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [1., 1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 1., 1.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 1.],
       [0., 1., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0.],
       [1., 1., 0., 1., 0., 1.],
       [0., 0., 0., 1., 0., 1.],
       [0., 1., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0., 1.],
       [1., 1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 1.],
       [0., 1., 0., 1., 0., 1.],
       [0., 0., 1., 0., 0., 1.],
       [0., 1., 0., 1., 0., 0.],
       [1., 0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0., 1.],
       [0., 1., 1., 0., 0., 0.],
       [1., 0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 1., 1.],
       [1.

In [ ]:
import numpy as np
import pandas as pd
df=pd.read_csv("/content/tips - tips.csv")


In [ ]:
df.head(2)

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3

In [ ]:
df.isnull().sum()

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

In [ ]:
df=df.drop(columns=['total_bill','tip'])

In [ ]:
df.head(2)

sex smoker  day    time  size
0  Female     No  Sun  Dinner     2
1    Male     No  Sun  Dinner     3

In [ ]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['sex']=le.fit_transform(df['sex'])
df['smoker']=le.fit_transform(df['smoker'])
df['day']=le.fit_transform(df['time'])
df['size']=le.fit_transform(df['size'])

In [ ]:
df.head(3)

sex  smoker  day    time  size
0    0       0    0  Dinner     1
1    1       0    0  Dinner     2
2    1       0    0  Dinner     2

In [223]:
df=pd.read_csv("/content/tips - tips.csv")
df.head(2)

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3

In [224]:
df['day'].value_counts()

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64

In [225]:
df['time'].value_counts()

time
Dinner    176
Lunch      68
Name: count, dtype: int64

In [226]:
df=df.drop(columns=['total_bill','tip','size'])

In [227]:
from sklearn.preprocessing import OrdinalEncoder
oe=OrdinalEncoder(categories=[
   ['Female','Male'],
   ['Yes','No'],
   ['Sat','Sun','Thur','Fri'],
   ['Dinner','Lunch']
])

In [228]:
oe.fit_transform(df)

array([[0., 1., 1., 0.],
       [1., 1., 1., 0.],
       [1., 1., 1., 0.],
       [1., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 1., 1., 0.],
       [1., 1., 1., 0.],
       [1., 1., 1., 0.],
       [1., 1., 1., 0.],
       [1., 1., 1., 0.],
       [1., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 1., 1., 0.],
       [1., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 1., 1., 0.],
       [0., 1., 1., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [0., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [0., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],


In [287]:
df=pd.read_csv("/content/tips - tips.csv")
df.head(3)
df=df.dropna()


In [288]:
df1=pd.get_dummies(df,columns=['sex','smoker','day','time'])
df1.head(3)

total_bill   tip  size  sex_Female  sex_Male  smoker_No  smoker_Yes  \
0       16.99  1.01     2        True     False       True       False   
1       10.34  1.66     3       False      True       True       False   
2       21.01  3.50     3       False      True       True       False   

   day_Fri  day_Sat  day_Sun  day_Thur  time_Dinner  time_Lunch  
0    False    False     True     False         True       False  
1    False    False     True     False         True       False  
2    False    False     True     False         True       False

In [292]:
df2=pd.get_dummies(df,columns=['sex','smoker','day','time'],drop_first=True)
df2.head(3)
b=df2.astype(int)
b.head(2)

total_bill  tip  size  sex_Male  smoker_Yes  day_Sat  day_Sun  day_Thur  \
0          16    1     2         0           0        0        1         0   
1          10    1     3         1           0        0        1         0   

   time_Lunch  
0           0  
1           0

In [299]:
from sklearn.preprocessing import OneHotEncoder
oh=OneHotEncoder(drop='first', sparse_output=False)
oh_new=(df2,[['sex','smoker','day','time']])
oh.fit_transform(df2)

array([[0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.]])

In [174]:
import numpy as np
import pandas as pd
df1=pd.read_csv("/content/credit_scoring - credit_scoring.csv")
df1.head(3)

Age  Gender Marital Status Education Level Employment Status  \
0   60    Male        Married          Master          Employed   
1   25    Male        Married     High School        Unemployed   
2   30  Female         Single          Master          Employed   

   Credit Utilization Ratio  Payment History  Number of Credit Accounts  \
0                      0.22             2685                          2   
1                      0.20             2371                          9   
2                      0.22             2771                          6   

   Loan Amount  Interest Rate  Loan Term   Type of Loan  
0      4675000           2.65         48  Personal Loan  
1      3619000           5.19         60      Auto Loan  
2       957000           2.76         12      Auto Loan

In [180]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [181]:
df1['Marital Status']=le.fit_transform(df1['Marital Status'])
df1['Education Level']=le.fit_transform(df1['Education Level'])
df1['Employment Status']=le.fit_transform(df1['Employment Status'])
df1['Type of Loan']=le.fit_transform(df1['Type of Loan'])
df1['Gender']=le.fit_transform(df1['Gender'])

In [178]:
df1.head(3)

Age  Gender  Marital Status  Education Level  Employment Status  \
0   60       1               1                2                  0   
1   25       1               1                1                  2   
2   30       0               2                2                  0   

   Credit Utilization Ratio  Payment History  Number of Credit Accounts  \
0                      0.22             2685                          2   
1                      0.20             2371                          9   
2                      0.22             2771                          6   

   Loan Amount  Interest Rate  Loan Term  Type of Loan  
0      4675000           2.65         48             2  
1      3619000           5.19         60             0  
2       957000           2.76         12             0

In [203]:
df1=pd.read_csv("/content/credit_scoring - credit_scoring.csv")
df1.head(3)

Age  Gender Marital Status Education Level Employment Status  \
0   60    Male        Married          Master          Employed   
1   25    Male        Married     High School        Unemployed   
2   30  Female         Single          Master          Employed   

   Credit Utilization Ratio  Payment History  Number of Credit Accounts  \
0                      0.22             2685                          2   
1                      0.20             2371                          9   
2                      0.22             2771                          6   

   Loan Amount  Interest Rate  Loan Term   Type of Loan  
0      4675000           2.65         48  Personal Loan  
1      3619000           5.19         60      Auto Loan  
2       957000           2.76         12      Auto Loan

In [204]:
df1=df1.drop(columns=['Age','Credit Utilization Ratio','Payment History','Number of Credit Accounts','Loan Amount','Interest Rate','Loan Term'])

In [205]:
from sklearn.preprocessing import OrdinalEncoder
ol=OrdinalEncoder(categories=[
    ['Male','Female'],
    ['Married','Single','Divorced'],
    ['Master','High School','PhD','Bachelor'],
    ['Employed','Unemployed','Self-Employed'],
    ['Personal Loan','Auto Loan','Home Loan']
])



In [206]:
ol.fit_transform(df1)

array([[0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 1.],
       [1., 1., 0., 0., 1.],
       ...,
       [1., 1., 0., 2., 0.],
       [1., 0., 2., 2., 1.],
       [1., 0., 0., 2., 1.]])

In [196]:
# from sklearn.model_selection import train_test_split
# x_train, x_test, y_train, y_test=train_test_split(x,y,test_size=0.2,random_state=56)

In [304]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
df1_sc=sc.fit_transform(df1)
df1_sc_new=pd.DataFrame(df1_sc,columns=df1.columns)
np.round(df1_sc_new.describe(),2)




total_bill     tip    size  sex_Male  smoker_Yes  day_Sat  day_Sun  \
count      244.00  244.00  244.00    244.00      244.00   244.00   244.00   
mean        -0.00    0.00   -0.00     -0.00        0.00     0.00     0.00   
std          1.00    1.00    1.00      1.00        1.00     1.00     1.00   
min         -1.88   -1.45   -1.65     -1.34       -0.78    -0.74    -0.67   
25%         -0.72   -0.72   -0.60     -1.34       -0.78    -0.74    -0.67   
50%         -0.22   -0.07   -0.60      0.74       -0.78    -0.74    -0.67   
75%          0.49    0.41    0.45      0.74        1.27     1.34     1.49   
max          3.49    5.07    3.61      0.74        1.27     1.34     1.49   

       day_Thur  time_Lunch  
count    244.00      244.00  
mean      -0.00        0.00  
std        1.00        1.00  
min       -0.58       -0.62  
25%       -0.58       -0.62  
50%       -0.58       -0.62  
75%        1.71        1.61  
max        1.71        1.61