<a href="https://colab.research.google.com/github/Divyanshpanchal960/python/blob/main/pandas3rdday.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#pandas-pandas is an open source library that is used for data manupulations
import pandas as pd
#data structure of pandas-
#1.series------it is one_dimensional array and it return only value not column name
#2.dataframe------it is multidimensional array and it returns columns name  with value.


In [ ]:
#Series-----
import pandas as pd

a=pd.Series([1,2,3,4,5,6,7,8,9])
a
import numpy as np
b=np.array(a)
b
type(b)
print(b.reshape((3,3)))
print(b.ndim)
print(b.size)
print("total rows and column:",b.shape)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
9
total rows and column: (9,)


In [ ]:
#Dataframe---------
import pandas as pd


a={  "Emp-id":[1,2,3,4,5],
      "name":["sam","raju","hari","ram","rohan"],
     "roles":["IT","sales","sales","IT","IT"],
     "working-hour":[8,8,8,9,9],
     "salary":["20000","20000","30000","40000","30000"]
}

In [ ]:
df=pd.DataFrame(a)
df

Emp-id   name  roles  working-hour salary
0       1    sam     IT             8  20000
1       2   raju  sales             8  20000
2       3   hari  sales             8  30000
3       4    ram     IT             9  40000
4       5  rohan     IT             9  30000

In [ ]:
#how can we Export this data into csv?
df.to_csv("emp_data.csv",index=False)



In [ ]:
#how can we Export data into excel?
df.to_excel("updated_emp_data.xlsx",index=False)

In [ ]:
#how we import data into csv?
df=pd.read_csv("/content/emp_data.csv")
df









Emp-id   name  roles  working-hour  salary
0       1    sam     IT             8   20000
1       2   raju  sales             8   20000
2       3   hari  sales             8   30000
3       4    ram     IT             9   40000
4       5  rohan     IT             9   30000

In [ ]:
#how to import data into excel?
df=pd.read_excel("/content/updated_emp_data.xlsx")
df

Emp-id   name  roles  working-hour  salary
0       1    sam     IT             8   20000
1       2   raju  sales             8   20000
2       3   hari  sales             8   30000
3       4    ram     IT             9   40000
4       5  rohan     IT             9   30000

In [ ]:
#instant data screper------google extension for screpering data

In [ ]:
a=pd.read_csv("/content/google.csv")
a

Restaurant Name  Ratings  \
0                                       Suvarna Mahal      4.7   
1                                  Skyfall Restaurant      4.3   
2                 J Brew & Kitchen Rooftop Restaurant      4.7   
3                                     Stardust Jaipur      4.2   
4                        Dawatnama- Family Restaurant      4.7   
5        Brewlicious Rooftop Bar Restaurant in Jaipur      4.8   
6                                  Peacock Restaurant      4.4   
7                                        The Magnolia      4.2   
8                                            The Lama      4.7   
9                                       La Multigrain      4.6   
10                                   Govindam Retreat      4.4   
11                                       Thali & more      4.4   
12                                    Fort Restaurant      4.3   
13                                              Akuri      4.6   
14                                 Monarch Restaurant      4.6   
15                                          Zolocrust      4.7   
16  Annpoornam - Best South Indian Restaurant In J...      4.6   
17                         The Forresta Kitchen & Bar      4.2   
18  The DeIicious Yard // family restaurants in ja...      4.7   
19                    Jaipur Modern - Store & Kitchen      4.4   

                                             Location  \
0                    RAMBAGH PALACE, Bhawani Singh Rd   
1   5th Floor, Ridhi Tower, SB 57, Tonk Rd, opposi...   
2     97 A, 5, Bhawani Singh Ln, near News 18 Channel   
3             Terrace floor, Signature Tower, Tonk Rd   
4   B-17, Sky Corner Building, Park Avenue Road, M...   
5   10th floor, Gadi, Okay Plus Tower, 5, Ajmer Rd...   
6                                           Rajasthan   
7   Garden Theatre, Smriti Van, Jawahar Lal Nehru ...   
8                       145, Ramesh Marg, above OTH E   
9   C-12, Lal Bahadur Nagar, Opposite World Trade ...   
10  First Floor, All Rajasthan Shilp Gram Udyog, B...   
11             1st floor plot no, C 46, Sarojini Marg   
12                                           RQXX+XRJ   
13                                Akuri, K10, Tonk Rd   
14                     Holiday Inn, Sardar Patel Marg   
15         Hotel, Clarks Amer, Jawahar Lal Nehru Marg   
16  Ground Floor, Moondra Tower, Plot No 012A, Ash...   
17  Devraj Niwas, Mirza Ismail Rd, near Khasa Koth...   
18  3, Panchawati Colony, Plot No.- 2, in front of...   
19  51, Dhuleshwar Garden, Sardar Patel Marg, near...   

                                        Type  
0      Elegant North Indian hotel restaurant  
1                                        NaN  
2                                        NaN  
3                                        NaN  
4                                        NaN  
5                                        NaN  
6     Arty rooftop venue serving global fare  
7                                        NaN  
8                                        NaN  
9          Warm restaurant for global dining  
10   Rajasthani decor & the region's cuisine  
11                                       NaN  
12       North Indian fine-dining restaurant  
13                                       NaN  
14                                       NaN  
15    Hotel's 24-hour vegetarian bakery-cafe  
16                                       NaN  
17  Relaxed global eatery with outdoor seats  
18                                       NaN  
19           Bohemian cafe with global flair

from matplotlib import pyplot as plt
a['Ratings'].plot(kind='hist', bins=20, title='Ratings')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
a['Ratings'].plot(kind='line', figsize=(8, 4), title='Ratings')
plt.gca().spines[['top', 'right']].set_visible(False)

In [ ]:
a=pd.read_csv("/content/flipkart.csv")
a

MODEL NAME  RATINGS  \
0       MOTOROLA Edge 60 Pro (Pantone Shadow, 256 GB)      4.3   
1           realme 13 Pro+ 5G (Emerald Green, 256 GB)      4.4   
2      MOTOROLA Edge 60 5G (PANTONE Shamrock, 256 GB)      4.3   
3   MOTOROLA Edge 60 5G (PANTONE Gibraltar Sea, 25...      4.3   
4   MOTOROLA Edge 60 Pro (Pantone Sparkling Grape,...      4.3   
5   MOTOROLA Edge 60 Pro (Pantone Dazzling Blue, 2...      4.3   
6   Motorola Edge 50 Pro 5G with 125W Charger (Lux...      4.4   
7           realme 13 Pro+ 5G (Emerald Green, 256 GB)      4.4   
8          Infinix GT 30 Pro 5G+ (Dark Flare, 256 GB)      4.4   
9               Nothing Phone (2a) 5G (Black, 256 GB)      4.4   
10              POCO X7 Pro 5G (Nebula Green, 256 GB)      4.4   
11       REDMI Note 14 SE 5G (Mystique White, 128 GB)      4.1   
12         CMF by Nothing Phone 2 Pro (Black, 256 GB)      4.4   
13  Motorola Edge 50 Pro 5G with 125W Charger (Can...      4.4   
14                      POCO F6 5G (Titanium, 256 GB)      4.3   
15     Samsung Galaxy A54 5G (Awesome Violet, 128 GB)      4.3   
16              Nothing Phone (2a) 5G (White, 256 GB)      4.4   
17        REDMI Note 13 Pro 5G (Arctic White, 128 GB)      4.3   
18               Nothing Phone (2a) 5G (Blue, 256 GB)      4.4   
19               Nothing Phone (2a) 5G (Blue, 256 GB)      4.4   
20        Infinix GT 30 Pro 5G+ (Blade White, 256 GB)      4.4   
21              Nothing Phone (2a) 5G (Black, 256 GB)      4.4   
22          OnePlus Nord CE4 (Celadon Marble, 256 GB)      4.4   
23         realme 12 Pro+ 5G (Submarine Blue, 256 GB)      4.4   

      REVIEW RATINGS                                        STORAGE  \
0     13,246 Ratings                          8 GB RAM | 256 GB ROM   
1     15,347 Ratings                          8 GB RAM | 256 GB ROM   
2      3,036 Ratings  12 GB RAM | 256 GB ROM | Expandable Upto 1 TB   
3      3,036 Ratings  12 GB RAM | 256 GB ROM | Expandable Upto 1 TB   
4     13,246 Ratings                          8 GB RAM | 256 GB ROM   
5     13,246 Ratings                          8 GB RAM | 256 GB ROM   
6     65,940 Ratings                         12 GB RAM | 256 GB ROM   
7      9,792 Ratings                         12 GB RAM | 256 GB ROM   
8        761 Ratings                         12 GB RAM | 256 GB ROM   
9   1,01,844 Ratings                          8 GB RAM | 256 GB ROM   
10     4,858 Ratings                         12 GB RAM | 256 GB ROM   
11     1,738 Ratings                          6 GB RAM | 128 GB ROM   
12    18,596 Ratings   8 GB RAM | 256 GB ROM | Expandable Upto 2 TB   
13    65,940 Ratings                         12 GB RAM | 256 GB ROM   
14    13,787 Ratings                          8 GB RAM | 256 GB ROM   
15     4,966 Ratings   8 GB RAM | 128 GB ROM | Expandable Upto 1 TB   
16  1,01,844 Ratings                          8 GB RAM | 256 GB ROM   
17    38,465 Ratings                          8 GB RAM | 128 GB ROM   
18    15,780 Ratings                         12 GB RAM | 256 GB ROM   
19  1,01,844 Ratings                          8 GB RAM | 256 GB ROM   
20     1,107 Ratings                          8 GB RAM | 256 GB ROM   
21    15,780 Ratings                         12 GB RAM | 256 GB ROM   
22    24,240 Ratings                          8 GB RAM | 256 GB ROM   
23    27,345 Ratings                          8 GB RAM | 256 GB ROM   

                                 DISPLAY   \
0             17.02 cm (6.7 inch) Display   
1    17.02 cm (6.7 inch) Full HD+ Display   
2            16.94 cm (6.67 inch) Display   
3            16.94 cm (6.67 inch) Display   
4             17.02 cm (6.7 inch) Display   
5             17.02 cm (6.7 inch) Display   
6             17.02 cm (6.7 inch) Display   
7    17.02 cm (6.7 inch) Full HD+ Display   
8            17.22 cm (6.78 inch) Display   
9    17.02 cm (6.7 inch) Full HD+ Display   
10           16.94 cm (6.67 inch) Display   
11  16.94 cm (6.67 inch) Full HD+ Display   
12            17.2 cm (6.77 inc